### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by lorenzori** [frederictost/images_annotation_programme#3]
Hi Frederic, thanks a ton for this repo, looks nice! 

I am not a web guy so have no idea how to run this. Could you add quick instructions to the `README`? At the moment I only double click on the `index.html`.

**Comment by Softverovich** [comment]
Clone the repo to your machine.
Open the folder.
Open index.html in a web browser of your choosing.
The app is now running.

**Comment by lorenzori** [comment]
@FilipMaslovaric thanks for the answer. Ok this was the way I was using, but images are not loading so I thought maybe I had to do something differently. But now I see the other issue, will follow that thread!
